name: BandwidthSaver-PE
version: '${project.version}'
main: com.mangocraft.plugins.bandwidthsaverpe.RIABandwidthSaver
api-version: '1.21'
folia-supported: true
author: Mangocraft
depend:
  - packetevents
permissions:
  bandwidthsaver.bypass:
    description: Player will not enter AFK mode
    default: false
  bandwidthsaver.admin:
    description: Allows access to admin commands
    default: op
commands:
  bandwidthsaver:
    usage: /bandwidthsaver
    permission: bandwidthsaver.admin
    permission-message: You don't have permission to use this command! <permission>
  afk:
    usage: /afk
    description: Toggle hardcore AFK mode